--JOINS
--Write and execute a SQL query to list the school names, community names and average attendance 
--for communities with a hardship index of 98.
SELECT CPS.NAME_OF_SCHOOL, CPS.COMMUNITY_AREA_NAME, CPS.AVERAGE_STUDENT_ATTENDANCE, 
CPS.AVERAGE_TEACHER_ATTENDANCE, CD.HARDSHIP_INDEX FROM CHICAGO_PUBLIC_SCHOOLS CPS 
LEFT OUTER JOIN CENSUS_DATA CD ON CPS.COMMUNITY_AREA_NAME = UPPER(CD.COMMUNITY_AREA_NAME) 
WHERE CD.HARDSHIP_INDEX = 98;

--Write and execute a SQL query to list all crimes that took place at a school. 
--Include case number, crime type and community name.
SELECT CCD.CASE_NUMBER, CCD.PRIMARY_TYPE, CD.COMMUNITY_AREA_NAME FROM CHICAGO_CRIME_DATA CCD
LEFT OUTER JOIN CENSUS_DATA CD ON CCD.COMMUNITY_AREA_NUMBER = CD.COMMUNITY_AREA_NUMBER WHERE
CCD.LOCATION_DESCRIPTION = 'SCHOOL, PRIVATE, BUILDING' OR CCD.LOCATION_DESCRIPTION
 = 'SCHOOL, PUBLIC, BUILDING' OR CCD.LOCATION_DESCRIPTION = 'SCHOOL, PUBLIC, GROUNDS' OR
 CCD.LOCATION_DESCRIPTION = 'SCHOOL, PRIVATE, GROUNDS';
 
--VIEWS
CREATE VIEW NEW_VIEW (School_Name, Safety_Rating, Family_Rating, Environment_Rating,
Instruction_Rating, Leaders_Rating, Teachers_Rating) AS 
SELECT NAME_OF_SCHOOL, SAFETY_ICON, FAMILY_INVOLVEMENT_ICON, ENVIRONMENT_ICON, 
INSTRUCTION_ICON,LEADERS_ICON, TEACHERS_ICON FROM CHICAGO_PUBLIC_SCHOOLS;
SELECT * FROM NEW_VIEW;
SELECT School_Name, Leaders_Rating FROM NEW_VIEW;

