--List the case number, type of crime and community area for all crimes in community area number 18.
SELECT CCD.CASE_NUMBER, CCD.PRIMARY_TYPE, CD.COMMUNITY_AREA_NAME FROM 
CHICAGO_CRIME_DATA CCD INNER JOIN CENSUS_DATA CD ON CCD.COMMUNITY_AREA_NUMBER = 
CD.COMMUNITY_AREA_NUMBER WHERE CCD.COMMUNITY_AREA_NUMBER = 18; 
--List all crimes that took place at a school. Include case number, crime type and community name.
SELECT CCD.CASE_NUMBER, CCD.PRIMARY_TYPE, CD.COMMUNITY_AREA_NAME FROM CHICAGO_CRIME_DATA CCD 
LEFT OUTER JOIN CENSUS_DATA CD ON CD.COMMUNITY_AREA_NUMBER = CCD.COMMUNITY_AREA_NUMBER WHERE 
CCD.LOCATION_DESCRIPTION = 'SCHOOL, PRIVATE, BUILDING' OR CCD.LOCATION_DESCRIPTION
 = 'SCHOOL, PUBLIC, BUILDING' OR CCD.LOCATION_DESCRIPTION = 'SCHOOL, PUBLIC, GROUNDS' OR
 CCD.LOCATION_DESCRIPTION = 'SCHOOL, PRIVATE, GROUNDS';
--For the communities of Oakland, Armour Square, Edgewater and CHICAGO list the associated 
--community_area_numbers and the case_numbers.
SELECT CCD.CASE_NUMBER, CD.COMMUNITY_AREA_NUMBER FROM CHICAGO_CRIME_DATA CCD FULL OUTER JOIN
CENSUS_DATA CD ON CCD.COMMUNITY_AREA_NUMBER = CD.COMMUNITY_AREA_NUMBER WHERE 
CD.COMMUNITY_AREA_NAME = 'Oakland' OR CD.COMMUNITY_AREA_NAME = 'Armour Square' OR
CD.COMMUNITY_AREA_NAME ='Edge Garden' OR CD.COMMUNITY_AREA_NAME = 'CHICAGO';